### ISSUE TITLE
dynamic backends in config file are not generated correctly by Puppet template

### ISSUE THREAD

**Issue by poymode** [caresharing/puppet-tapsilog#1]
A sample tapsilog.yml would look like

```yaml
backends:
  - adapter: fluentd
    host: localhost
  - adapter: file
```

Translating that to Puppet would be

```puppet
class tapsilog {
  $backends = [
    {
      "adapter" => "fluentd",
      "host" => "localhost"
    },
    {
      "adapter" => "file"
    }
  ]
}
```

A sample EPP template that would iterate over the backends
```erb
backends:
<% $tapsilog::backends.each |$backend| { %>
<%= $backend -%>
<% } %>
```

but it outputs the $backend value literally as show

```yaml
backends:
- {adapter => fluentd, host => localhost}
- {adapter => file}
```
